{
 "title": "Energy consumption",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current power consumption (tariff 1)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "kwatt",
   "valueName": "current",
   "targets": [
    {
     "expr": "power_delivered{tariff_indicator=\"1\"}"
    }
   ]
  },
  {
   "title": "Current power consumption (tariff 2)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "kwatt",
   "valueName": "current",
   "targets": [
    {
     "expr": "power_delivered{tariff_indicator=\"2\"}"
    }
   ]
  },
  {
   "title": "Power consumption L1, L2, L3",
   "type": "graph",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    { "expr": "l1_power_delivered" },
    { "expr": "l2_power_delivered" },
    { "expr": "l3_power_delivered" }
   ]
  },
  {
   "title": "Power tariff 1 reading",
   "type": "singlestat",
   "description": "Total power consumption reading tariff-1",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    { "expr": "tariff1_delivered_reading" }
   ]
  },
  {
   "title": "Power tariff 2 reading",
   "type": "singlestat",
   "description": "Total power consumption reading tariff-2",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    { "expr": "tariff2_delivered_reading" }
   ]
  },
  {
   "title": "Gas reading",
   "type": "singlestat",
   "description": "Total gas consumption reading",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
   "format": "m3",
   "valueName": "avg",
   "targets": [
    { "expr": "gas_delivered_reading", "legendFormat": "Verbruik gas" }
   ]
  },
  {
   "title": "Gas consumption/hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "m3" }
   ],
   "targets": [
    {
     "expr": "delta(gas_delivered_reading[1h])"
    }
   ]
  }
 ]
}